-- Migration 021: Blueprint 30 shadow-only virtual trade ledger. Idempotent.
create table if not exists shadow_trades (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    asset text not null,
    condition_id text not null,
    token_id text not null,
    side text not null check (side in ('up', 'down')),
    window_start timestamptz not null,
    window_end timestamptz not null,
    entered_at timestamptz not null,
    time_left_sec double precision not null,
    model_p double precision not null,
    spot numeric not null,
    open_price numeric not null,
    sigma double precision not null,
    book_best_ask double precision,
    sim_fill_price double precision not null,
    sim_shares numeric not null,
    stake_usdc numeric not null,
    fee_usdc numeric not null,
    edge double precision not null,
    status text not null default 'open'
        check (status in ('open', 'win', 'loss', 'void')),
    resolved_at timestamptz,
    pnl_usdc numeric
);

create unique index if not exists uq_shadow_trades_condition
    on shadow_trades (condition_id);
create index if not exists idx_shadow_trades_status_window_end
    on shadow_trades (status, window_end);
create index if not exists idx_shadow_trades_created_at
    on shadow_trades (created_at desc);
