-- Migration 025: Blueprint 33 — standalone BTC-bot real-money pilot. Idempotent.
-- Separate product tables: the crypto bot never touches copytrade `users`/`copy_trades`.

create table if not exists crypto_users (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    telegram_id bigint not null unique,
    username text,
    -- BP27-style per-user wallet: EOA + relayer deposit wallet (POLY_1271 funder).
    wallet_address text,
    wallet_private_key_enc text,
    deposit_wallet_address text,
    clob_api_key text,
    clob_secret text,
    clob_passphrase text,
    wallet_registered boolean not null default false,
    wallet_created_at timestamptz,
    -- Product state.
    trading_on boolean not null default false,
    stake_usdc numeric not null default 5.0,
    -- Deposit detection baseline (EOA stablecoin), same trick as copytrade monitor.
    eoa_stable_baseline numeric not null default 0
);

create table if not exists crypto_trades (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    user_id bigint not null references crypto_users(id),
    asset text not null,
    condition_id text not null,
    token_id text not null,
    side text not null check (side in ('up', 'down')),
    window_end timestamptz not null,
    -- Signal context (for later comparison with shadow_trades).
    signal_price double precision,
    model_p double precision,
    edge double precision,
    -- Real execution facts from the CLOB response (BP28 exact fill accounting).
    intended_usdc numeric,
    filled_usdc numeric,
    shares numeric,
    fill_price double precision,
    fee_usdc numeric not null default 0,
    -- Lifecycle: open -> win/loss/void; skipped = signal received but not traded.
    status text not null default 'open'
        check (status in ('open', 'win', 'loss', 'void', 'skipped')),
    skip_reason text,
    resolved_at timestamptz,
    redeem_tx text,
    pnl_usdc numeric
);

-- One position per user per market — the executor's idempotency backstop.
create unique index if not exists uq_crypto_trades_user_condition
    on crypto_trades (user_id, condition_id);
create index if not exists idx_crypto_trades_status_window_end
    on crypto_trades (status, window_end);
create index if not exists idx_crypto_trades_user_created
    on crypto_trades (user_id, created_at desc);
