-- Migration 028: Blueprint 48 — donor scout (discovery from our own tape).
-- Idempotent.
--
-- wallet_sightings: every large taker BUY observed in OUR fast-market universe
-- (passive record-only revival of the Model-A whale feed). Candidates are by
-- construction copyable: right window, right liquidity, visible cadence.
--
-- donor_candidates: nightly-scored candidate pool with anti-MM fingerprints
-- and resolution WR on the sighted markets.
--
-- trade_signals.probation: signals recorded for mode='candidate' tracked
-- wallets (shadow probation) — never dispatched to users, never counted
-- toward consensus.

create table if not exists wallet_sightings (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    wallet text not null,
    tx_hash text not null unique,
    condition_id text not null,
    token_id text,
    outcome text,
    price double precision,
    size_usdc numeric,
    title text,
    traded_at timestamptz
);

create index if not exists idx_wallet_sightings_wallet_created
    on wallet_sightings (wallet, created_at desc);
create index if not exists idx_wallet_sightings_created
    on wallet_sightings (created_at desc);

create table if not exists donor_candidates (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    wallet text not null unique,
    name text,
    sightings_14d integer not null default 0,
    volume_14d numeric not null default 0,
    avg_trade_usdc numeric not null default 0,
    resolved_count integer not null default 0,
    resolved_wins integer not null default 0,
    directionality double precision,
    trades_per_day double precision,
    is_mm boolean not null default false,
    score double precision not null default 0,
    status text not null default 'new'
        check (status in ('new', 'candidate', 'promoted', 'dismissed'))
);

alter table trade_signals add column if not exists probation boolean not null default false;
